//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace backe
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFaceToFace
    {
        public int fId { get; set; }
        public int fProductId { get; set; }
        public string fDelivery { get; set; }
        public string fCoordinateX { get; set; }
        public string fCoordinateY { get; set; }
    
        public virtual tProduct tProduct { get; set; }
    }
}
