//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace backe
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFeedback
    {
        public int fId { get; set; }
        public int fReplyId { get; set; }
        public int fFeedbackMemberId { get; set; }
        public System.DateTime fFeedbackTime { get; set; }
        public string fContent { get; set; }
    
        public virtual tMember tMember { get; set; }
        public virtual tReply tReply { get; set; }
    }
}
