//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace backe
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMemberList
    {
        public int fId { get; set; }
        public int fCommunityId { get; set; }
        public int fMemberId { get; set; }
        public System.DateTime fJoinDate { get; set; }
        public int fAccessRightId { get; set; }
    
        public virtual tAccessRight tAccessRight { get; set; }
        public virtual tCommunity tCommunity { get; set; }
        public virtual tMember tMember { get; set; }
    }
}
