//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace backe
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tProduct()
        {
            this.tFaceToFace = new HashSet<tFaceToFace>();
            this.tProduct5Tag = new HashSet<tProduct5Tag>();
            this.tQnA = new HashSet<tQnA>();
            this.tSearchingRecord = new HashSet<tSearchingRecord>();
        }
    
        public int fId { get; set; }
        public string fName { get; set; }
        public int fPrice { get; set; }
        public System.DateTime fDate { get; set; }
        public string fDetail { get; set; }
        public string fPath { get; set; }
        public int fMemberId { get; set; }
        public int fDelivery { get; set; }
        public int fProduct5TagId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tFaceToFace> tFaceToFace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tProduct5Tag> tProduct5Tag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tQnA> tQnA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSearchingRecord> tSearchingRecord { get; set; }
    }
}
