//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace backe
{
    using System;
    using System.Collections.Generic;
    
    public partial class tQnA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tQnA()
        {
            this.tReply1 = new HashSet<tReply1>();
        }
    
        public int fId { get; set; }
        public int fProductId { get; set; }
        public int fMemberId { get; set; }
        public System.DateTime fTime { get; set; }
        public string fMessage { get; set; }
        public Nullable<int> fReplyId { get; set; }
    
        public virtual tProduct tProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tReply1> tReply1 { get; set; }
    }
}
