//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backstage
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeaTurtleOnTheWayEntities2 : DbContext
    {
        public SeaTurtleOnTheWayEntities2()
            : base("name=SeaTurtleOnTheWayEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tActivity> tActivity { get; set; }
        public virtual DbSet<tActivityHadLabel> tActivityHadLabel { get; set; }
        public virtual DbSet<tActivityLabel> tActivityLabel { get; set; }
        public virtual DbSet<tActivityMainLabel> tActivityMainLabel { get; set; }
        public virtual DbSet<tActivityMessage> tActivityMessage { get; set; }
        public virtual DbSet<tActivityType> tActivityType { get; set; }
        public virtual DbSet<tAttestType> tAttestType { get; set; }
        public virtual DbSet<tJoinList> tJoinList { get; set; }
        public virtual DbSet<tJoinType> tJoinType { get; set; }
        public virtual DbSet<tScore> tScore { get; set; }
        public virtual DbSet<tSearchList> tSearchList { get; set; }
        public virtual DbSet<tAccessRight> tAccessRight { get; set; }
        public virtual DbSet<tCommunity> tCommunity { get; set; }
        public virtual DbSet<tFeedback> tFeedback { get; set; }
        public virtual DbSet<tMemberList> tMemberList { get; set; }
        public virtual DbSet<tPost> tPost { get; set; }
        public virtual DbSet<tReply> tReply { get; set; }
        public virtual DbSet<tStatus> tStatus { get; set; }
        public virtual DbSet<tAccountLikeList> tAccountLikeList { get; set; }
        public virtual DbSet<tAccountType> tAccountType { get; set; }
        public virtual DbSet<tMember> tMember { get; set; }
        public virtual DbSet<tMessage> tMessage { get; set; }
    }
}
