//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backstage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tActivityMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tActivityMessage()
        {
            this.tActivityMessage1 = new HashSet<tActivityMessage>();
        }
    
        public int fId { get; set; }
        public int fActivityId { get; set; }
        public int fMemberId { get; set; }
        public string fContent { get; set; }
        public string fTime { get; set; }
        public Nullable<int> fReplyerId { get; set; }
    
        public virtual tMember tMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tActivityMessage> tActivityMessage1 { get; set; }
        public virtual tActivityMessage tActivityMessage2 { get; set; }
        public virtual tAttestType tAttestType { get; set; }
    }
}
