//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backstage
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tReply
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tReply()
        {
            this.tFeedback = new HashSet<tFeedback>();
        }
        [DisplayName("序")]
        public int fId { get; set; }
        [DisplayName("文章")]
        public int fPostId { get; set; }
        [DisplayName("留言人")]
        public int fReplyMemberId { get; set; }
        [DisplayName("回覆時間")]
        public string fReplyTime { get; set; }
        [DisplayName("內容")]
        public string fContent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tFeedback> tFeedback { get; set; }
        public virtual tPost tPost { get; set; }
        public virtual tMember tMember { get; set; }
    }
}
