//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backstage
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tActivity()
        {
            this.tActivityHadLabel = new HashSet<tActivityHadLabel>();
            this.tScore = new HashSet<tScore>();
            this.tSearchList = new HashSet<tSearchList>();
            this.tJoinList = new HashSet<tJoinList>();
        }
        [DisplayName("序號")]
        public int fId { get; set; }
        [DisplayName("活動名稱")]
        public string fActName { get; set; }
        [DisplayName("申請時間")]
        public System.DateTime fCreatDate { get; set; }
        [DisplayName("活動起始時間")]
        public System.DateTime fActivityDate { get; set; }
        [DisplayName("活動起結束時間")]
        public System.DateTime fActivityEndDate { get; set; }
        [DisplayName("發起人")]
        public int fMemberId { get; set; }
        [DisplayName("介紹")]
        public string fIntroduction { get; set; }
        [DisplayName("最大人數")]
        public Nullable<int> fMaxLimit { get; set; }
        [DisplayName("最小人數")]
        public Nullable<int> fMinLimit { get; set; }
        [DisplayName("認證狀態")]
        public int fActAttestId { get; set; }
        [DisplayName("活動狀態")]
        public int fActTypeId { get; set; }
        [DisplayName("城市")]
        public string fActLocation { get; set; }
        [DisplayName("x座標")]
        public string fCoordinateX { get; set; }
        [DisplayName("y座標")]
        public string fCoordinateY { get; set; }
        [DisplayName("主要類別")]
        public int fActLabelId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tActivityHadLabel> tActivityHadLabel { get; set; }
        public virtual tActivityMainLabel tActivityMainLabel { get; set; }
        public virtual tMember tMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tScore> tScore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSearchList> tSearchList { get; set; }
        public virtual tActivityType tActivityType { get; set; }
        public virtual tAttestType tAttestType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tJoinList> tJoinList { get; set; }
    }
}
